apiVersion: v1
kind: Service
metadata:
  name: python-package-flask-test-service-az
  labels:
    app: python-package-flask-test-az
spec:
  type: NodePort
  selector:
    app: python-package-flask-test-az    
  ports:
  - port: 5000
    targetPort: http
    nodePort: 32410
    protocol: TCP    
    name: http


