apiVersion: v1
kind: Service
metadata:
  name: myinsuranceappsree
  labels:
    app: myinsuranceapp
spec:
  selector:
    app: myinsuranceapp
  type: NodePort
  ports:
  - port: 5000
    targetPort: http
    nodePort: 31172
    protocol: TCP
    name: http